/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesVentana;

import ClasesGrafo.Grafo;
import ClasesGrafo.Lista;
import ClasesGrafo.Recorridos;
import Lectura.*;
import Mostrargrafo.mostrarG;
import Roles.Driver;
import Roles.Cliente;


public class PrimeraVentana extends javax.swing.JFrame {

    /**
     * Creates new form PrimeraVentana
     */
    
    public static ListDatos pedidos;
    public static  Grafo grafo;
    mostrarG mostrar;
    
    Base_de_Datos bdatos= new Base_de_Datos();
    public PrimeraVentana() {
        initComponents();
        this.setLocationRelativeTo(null);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salirboton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotonCargar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        BotonMostrarGrafo = new javax.swing.JButton();
        BotonRecorrerGrafo = new javax.swing.JButton();
        BotonRoles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salirboton.setText("Salir");
        Salirboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        jLabel1.setText("Samancito Delivery ");

        BotonCargar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BotonCargar.setText("Cargar archivo ");
        BotonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarActionPerformed(evt);
            }
        });

        BotonActualizar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BotonActualizar.setText("Actualizar archivo");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        BotonMostrarGrafo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BotonMostrarGrafo.setText("Mostrar grafo");
        BotonMostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarGrafoActionPerformed(evt);
            }
        });

        BotonRecorrerGrafo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BotonRecorrerGrafo.setText("Recorrer grafo");
        BotonRecorrerGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecorrerGrafoActionPerformed(evt);
            }
        });

        BotonRoles.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BotonRoles.setText("Seleccionar  rol usuario");
        BotonRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRolesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(BotonCargar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(BotonMostrarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(BotonRecorrerGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salirboton)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(BotonRoles))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(BotonActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Salirboton)
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(BotonCargar)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMostrarGrafo)
                    .addComponent(BotonRecorrerGrafo))
                .addGap(44, 44, 44)
                .addComponent(BotonRoles)
                .addGap(58, 58, 58)
                .addComponent(BotonActualizar)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirbotonActionPerformed

    private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
        // TODO add your handling code here:
        
        pedidos=bdatos.datos();
        grafo=bdatos.getGrafo();
    }//GEN-LAST:event_BotonCargarActionPerformed

    private void BotonMostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarGrafoActionPerformed
        // TODO add your handling code here:
        mostrar=new mostrarG(grafo);
        
    }//GEN-LAST:event_BotonMostrarGrafoActionPerformed

    private void BotonRecorrerGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecorrerGrafoActionPerformed
        // TODO add your handling code here:
        
        VentanaRecorrer vrecorrer= new VentanaRecorrer();
        vrecorrer.setVisible(true);
    }//GEN-LAST:event_BotonRecorrerGrafoActionPerformed

    private void BotonRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRolesActionPerformed
        UsuarioRoles ventro= new UsuarioRoles();
        ventro.setVisible(true);
    }//GEN-LAST:event_BotonRolesActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        // TODO add your handling code here:
        
        ActualizarArchivo actu = new ActualizarArchivo(grafo,pedidos,bdatos);
    }//GEN-LAST:event_BotonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonCargar;
    private javax.swing.JButton BotonMostrarGrafo;
    private javax.swing.JButton BotonRecorrerGrafo;
    private javax.swing.JButton BotonRoles;
    private javax.swing.JButton Salirboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
