/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesVentana;
import Roles.*;
import  ClasesGrafo.*;
import javax.swing.JOptionPane;

public class VentanaAdministrador extends javax.swing.JFrame {

    Grafo g;
    Lista lndos;
    Administrador admi;
    public VentanaAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        PrimeraVentana venta1= new PrimeraVentana();
        this.g=venta1.grafo;
        this.lndos=g.getLnodos();
        this.admi= new Administrador(lndos,g);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregarLocales = new javax.swing.JButton();
        BotonAgregarRuta = new javax.swing.JButton();
        BotonAgregarPlato = new javax.swing.JButton();
        BotonElminarPlato = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregarLocales.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BotonAgregarLocales.setText("Agregar Locales");
        BotonAgregarLocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarLocalesActionPerformed(evt);
            }
        });

        BotonAgregarRuta.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BotonAgregarRuta.setText("Agregar Ruta ");
        BotonAgregarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarRutaActionPerformed(evt);
            }
        });

        BotonAgregarPlato.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BotonAgregarPlato.setText("Agregar plato ");
        BotonAgregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarPlatoActionPerformed(evt);
            }
        });

        BotonElminarPlato.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BotonElminarPlato.setText("Eliminar Plato");
        BotonElminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonElminarPlatoActionPerformed(evt);
            }
        });

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(BotonAgregarLocales))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonElminarPlato)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BotonAgregarPlato)
                                .addComponent(BotonAgregarRuta)))))
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonRegresar)
                .addGap(245, 245, 245))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BotonRegresar)
                .addGap(139, 139, 139)
                .addComponent(BotonAgregarLocales)
                .addGap(59, 59, 59)
                .addComponent(BotonAgregarRuta)
                .addGap(65, 65, 65)
                .addComponent(BotonAgregarPlato)
                .addGap(66, 66, 66)
                .addComponent(BotonElminarPlato)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonAgregarLocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarLocalesActionPerformed
        // TODO add your handling code here:
        admi.agregar_locales();
        JOptionPane.showMessageDialog(null, "Oparacion realizada con exito. Regrese a la primera ventana para guardar los cambios.");
    }//GEN-LAST:event_BotonAgregarLocalesActionPerformed

    private void BotonAgregarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarRutaActionPerformed
        // TODO add your handling code here:
        admi.agregar_ruta();
        JOptionPane.showMessageDialog(null, "Oparacion realizada con exito. Regrese a la primera ventana para guardar los cambios.");
    }//GEN-LAST:event_BotonAgregarRutaActionPerformed

    private void BotonAgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarPlatoActionPerformed
        // TODO add your handling code here:
        admi.agregar_plato();
        JOptionPane.showMessageDialog(null, "Oparacion realizada con exito. Regrese a la primera ventana para guardar los cambios.");
    }//GEN-LAST:event_BotonAgregarPlatoActionPerformed

    private void BotonElminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonElminarPlatoActionPerformed
        // TODO add your handling code here:
        admi.eliminar_plato();
        JOptionPane.showMessageDialog(null, "Oparacion realizada con exito. Regrese a la primera ventana para guardar los cambios.");
    }//GEN-LAST:event_BotonElminarPlatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarLocales;
    private javax.swing.JButton BotonAgregarPlato;
    private javax.swing.JButton BotonAgregarRuta;
    private javax.swing.JButton BotonElminarPlato;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
