/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package InterfacesVentana;
import ClasesGrafo.Recorridos;
import ClasesGrafo.Grafo;
public class VentanaRecorrer extends javax.swing.JFrame {

    Recorridos recorrido= new Recorridos();
    Grafo g;
    
    public VentanaRecorrer( ) {
        initComponents();
        this.setLocationRelativeTo(null);
        PrimeraVentana ventana = new PrimeraVentana();
        this.g=ventana.grafo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonVolver = new javax.swing.JButton();
        ANchuraBoton = new javax.swing.JButton();
        ProfundidadBoton = new javax.swing.JButton();
        TextoAnchura1 = new javax.swing.JTextField();
        TextoProfundidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonVolver.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        ANchuraBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ANchuraBoton.setText("Recorrido de anchura ");
        ANchuraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANchuraBotonActionPerformed(evt);
            }
        });

        ProfundidadBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfundidadBoton.setText("Recorrido de profundidad");
        ProfundidadBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfundidadBotonActionPerformed(evt);
            }
        });

        TextoAnchura1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        TextoAnchura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoAnchura1ActionPerformed(evt);
            }
        });

        TextoProfundidad.setFont(new java.awt.Font("Times New Roman", 0, 9)); // NOI18N
        TextoProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoProfundidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TextoAnchura1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(TextoProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(ANchuraBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProfundidadBoton)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANchuraBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfundidadBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoAnchura1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(TextoProfundidad))
                .addGap(53, 53, 53))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
          //this.setVisible(false);
          this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void ANchuraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANchuraBotonActionPerformed
        //g.ImprimirMatriz();
        TextoAnchura1.setText(recorrido.amplitud(g));
    }//GEN-LAST:event_ANchuraBotonActionPerformed

    private void TextoAnchura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoAnchura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoAnchura1ActionPerformed

    private void ProfundidadBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfundidadBotonActionPerformed
        // TODO add your handling code here:
        
        TextoProfundidad.setText( recorrido.profundidad(g));
    }//GEN-LAST:event_ProfundidadBotonActionPerformed

    private void TextoProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoProfundidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoProfundidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRecorrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRecorrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRecorrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRecorrer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRecorrer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANchuraBoton;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JButton ProfundidadBoton;
    private javax.swing.JTextField TextoAnchura1;
    private javax.swing.JTextField TextoProfundidad;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
